//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_Operazioni
    {
        public int ID { get; set; }
        public string MVCODART { get; set; }
        public string MVCODUBI { get; set; }
        public int MVCODUTE { get; set; }
        public Nullable<System.DateTime> MVDATMOV { get; set; }
        public string MVTIPMOV { get; set; }
        public string MVCODCOM { get; set; }
        public Nullable<decimal> MVQTAMOV { get; set; }
    
        public virtual Articoli Articoli { get; set; }
        public virtual Com_essa Com_essa { get; set; }
        public virtual Utenti Utenti { get; set; }
    }
}
